Kinetics/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kinetics.Data;
using Kinetics.Models;
using Kinetics.Models.DTO;

namespace Kinetics.Controllers
{
    public class BranchesController : Controller
    {
        private readonly KineticsContext _context;

        public BranchesController (KineticsContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var branches = _context.Branches
                .AsNoTracking();

            return View(await branches.ToListAsync());
        }

        // GET: Branches/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BranchDto branchDto)
        {
            if (ModelState.IsValid)
            {
                //Manually map DTO to the Branch Model
                var branch = new Branch
                {
                    BranchName = branchDto.BranchName,
                    BranchLocation = branchDto.BranchLocation
                };

                //Add the new branch to the context
                _context.Add(branch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(branchDto);
        }

        // GET: Branches/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches.FindAsync(id);
            if (branch == null)
            {
                return NotFound();
            }
            return View(branch);
        }

        // POST: Branches/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, BranchDto branchDto)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branchToUpdate = await _context.Branches.FirstOrDefaultAsync(b => b.BranchID == id);

            if (branchToUpdate == null)
            {
                return NotFound();
            }

            //Map the DTO values to the entity object
            branchToUpdate.BranchName = branchDto.BranchName;
            branchToUpdate.BranchLocation = branchDto.BranchLocation;

            try
            {
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists, "
                    + "See your system administrator.");
            }
            return View(branchDto);
        }

        // GET: Branches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches.FindAsync(id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        //POST: Branches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var branch = await _context.Branches.FindAsync(id);
            if (branch != null)
            {
                _context.Remove(branch);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Kinetics/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kinetics.Data;
using Kinetics.Models;
using Kinetics.Models.DTO;

namespace Kinetics.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly KineticsContext _context;

        public DepartmentsController(KineticsContext context)
        {
            _context = context;
        }

       // GET: Departments/
       public async Task<IActionResult> Index()
        {
            var departments = _context.Departments
                .AsNoTracking();

            return View(await departments.ToListAsync());
        }

        // GET: Department/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Department/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DepartmentDto departmentDto)
        {
            if (ModelState.IsValid)
            {
                // Manually map DTO to the Department Model
                var department = new Department
                {
                    DepartmentName = departmentDto.DepartmentName
                };

                // Add the new Department to Context
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(departmentDto);
        }

        // GET: Departments/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound(); 
            }
            return View(department);
        }

        // POST: Departments/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, DepartmentDto departmentDto)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departmentToUpdate = await _context.Departments.FirstOrDefaultAsync(d => d.DepartmentID == id);

            if (departmentToUpdate == null)
            {
                return NotFound();
            }

            // Map DTO to Model
            departmentToUpdate.DepartmentName = departmentDto.DepartmentName;

            try
            {
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists, "
                    + "See your system administrator.");
            }
            return View(departmentDto);
        }

        // GET: Departments/Delete/1
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                NotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Departments.FindAsync(id);
            if (department != null)
            {
                _context.Remove(department);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

Kinetics/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kinetics.Data;
using Kinetics.Models;
using Kinetics.Models.DTO;

namespace Kinetics.Controllers
{
    public class RolesController : Controller
    {
        private readonly KineticsContext _context;

        public RolesController(KineticsContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            var roles = _context.Roles
                .AsNoTracking();

            return View(await roles.ToListAsync());
        }

        // GET: Role/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Role/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleDto roleDto)
        {
            if (ModelState.IsValid)
            {
                // Map DTO to Role Model
                var role = new Role
                {
                    RoleName = roleDto.RoleName
                };

                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(roleDto);
        }

        // GET: Role/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Role/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, RoleDto roleDto)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var roleToUpdate = await _context.Roles.FirstOrDefaultAsync(r => r.RoleID == id);

                if (roleToUpdate == null)
                {
                    return NotFound();
                }

                // Map Dto to Role Model
                roleToUpdate.RoleName = roleDto.RoleName;

                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Unable to Update Role Model");
                }
            }
            return View(roleDto);
        }

        // GET: Role/Delete/1
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var role = await _context.Roles.FindAsync(id);
            if(role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Role/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfrmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                _context.Remove(role);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Kinetics/Controllers/SalariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kinetics.Data;
using Kinetics.Models;

namespace Kinetics.Controllers
{
    public class SalariesController : Controller
    {
        private readonly KineticsContext _context;

        public SalariesController(KineticsContext context)
        {
            _context = context;
        }

        // GET: Salaries
        public async Task<IActionResult> Index()
        {
            var kineticsContext = _context.Salaries.Include(s => s.Employee);
            return View(await kineticsContext.ToListAsync());
        }

        // GET: Salaries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salaries
                .Include(s => s.Employee)
                .FirstOrDefaultAsync(m => m.SalaryID == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        // GET: Salaries/Create
        public IActionResult Create()
        {
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Email");
            return View();
        }

        // POST: Salaries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SalaryID,GrossSalary,EffectiveFrom,EffectiveTo,EmployeeID")] Salary salary)
        {
            if (ModelState.IsValid)
            {
                _context.Add(salary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Email", salary.EmployeeID);
            return View(salary);
        }

        // GET: Salaries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salaries.FindAsync(id);
            if (salary == null)
            {
                return NotFound();
            }
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Email", salary.EmployeeID);
            return View(salary);
        }

        // POST: Salaries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SalaryID,GrossSalary,EffectiveFrom,EffectiveTo,EmployeeID")] Salary salary)
        {
            if (id != salary.SalaryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalaryExists(salary.SalaryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Email", salary.EmployeeID);
            return View(salary);
        }

        // GET: Salaries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salaries
                .Include(s => s.Employee)
                .FirstOrDefaultAsync(m => m.SalaryID == id);
            if (salary == null)
            {
                return NotFound();
            }

            return View(salary);
        }

        // POST: Salaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var salary = await _context.Salaries.FindAsync(id);
            if (salary != null)
            {
                _context.Salaries.Remove(salary);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalaryExists(int id)
        {
            return _context.Salaries.Any(e => e.SalaryID == id);
        }
    }
}

Kinetics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kinetics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kinetics.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow vc-navbar">
            <div class="container-fluid">
                <a class="navbar-brand vc-brand-color" asp-area="" asp-controller="Home" asp-action="Index">Kinetics</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 vc-navbar-list">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Organization" asp-action="Index">Organization</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">Leave Application</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">Financial Assistance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">Attendance</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav vc-navbar-list">
                        <li class="nav-item">
                            <a class="nav-link">SuperUser</a>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Kinetics/Views/Shared/_SharedBottom.cshtml
        </div>
    </div>
</div>

Kinetics/Views/Shared/_SharedTop.cshtml
<div class="vc-container">
    <div class="vc-sidebar">
        <ul class="vc-sidebar-list">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Branches" asp-action="Index"><ion-icon name="briefcase-outline"></ion-icon> Branch</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Departments" asp-action="Index"><ion-icon name="file-tray-full-outline"></ion-icon> Department</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="JobPositions" asp-action="Index"><ion-icon name="id-card"></ion-icon> Position</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Roles" asp-action="Index"><ion-icon name="hand-left-outline"></ion-icon> Role</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Employees" asp-action="Index"><ion-icon name="people-outline"></ion-icon> Employee</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Salaries" asp-action="Index"><ion-icon name="cash-outline"></ion-icon> Payroll</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="" asp-action="Index"><ion-icon name="construct-outline"></ion-icon> Employee Property</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="" asp-action="Index"> <ion-icon name="information-circle-outline"></ion-icon> Training</a>
            </li>
        </ul>
    </div>
    <div class="vc-content">
        <div class="container">